services:
  # Base image containing dependencies.
  base:
    image: ghcr.io/bjoernellens1/ros_rmp/rmp:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - ghcr.io/bjoernellens1/ros_rmp/rmp:base
      args:
        ROS_DISTRO: noetic
      target: base
      x-bake:
        platforms:
          - linux/amd64
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_HOSTNAME=10.71.1.218
      - ROS_IP=10.71.1.218
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    restart: no
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

    # lidar
  lidar:
    extends: base
    # depends_on_on:
    #   - lidar_filter
    command: >
      roslaunch rplidar_ros rplidar_a2m8.launch
    devices:
      - /dev/rplidar:/dev/ttyUSB0 #udevrules needed for this to work:
      # file /etc/udev/rules.d/98-rplidar.rules
#       SUBSYSTEM=="tty", ATTRS{serial}=="3453995662b3af4f81f4a69eba5f3f29", SYMLINK+="rplidar", MODE="0666"
    restart: unless-stopped

  master:
    extends: base
    command: >
      roscore

  segway:
    extends: base
    devices:
      - /dev/segway:/dev/ttyUSB0 #udevrules needed for this to work:
      # file /etc/udev/rules.d/99-segway.rules
#       SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="0001", SYMLINK+="segway", MODE="0666"
    command: |
      bash -c "
      source /rmp_ws/devel/setup.bash &&
      rosrun segwayrmp SmartCar"
    restart: unless-stopped

  teleop:
    extends: base
    devices:
      - /dev/input/js0:/dev/input/js0
    command: |
      bash -c "
      source /rmp_ws/devel/setup.bash &&
      roslaunch rmp220_middleware teleop.launch"
    restart: unless-stopped

  slam:
    extends: base
    depends_on:
      - segway
      - lidar
      
  description:
    extends: base

  navigation:
    extends: base
    depends_on:
      - description
      - slam

  debug:
    extends: base
    volumes:
      - ./src:/debug_ws/src
    command: >
      /bin/bash

  rviz:
    extends: base
    command: >
      rviz
    devices:
      - /dev/dri:/dev/dri
